Controllers/ClienteController.cs
using System.Linq;
using System.Threading.Tasks;
using EstoqueWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EstoqueWeb.Controllers
{
    public class ClienteController : Controller {
        private readonly EstoqueWebContext _context;

        public ClienteController(EstoqueWebContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.OrderBy(o => o.Nome).AsNoTracking().ToListAsync());
        }
        [HttpGet]
        public async Task<IActionResult> Cadastrar(int? id)
        {
            if(id.HasValue)
            {
                var cliente = await _context.Clientes.FindAsync(id);
                if(cliente == null)
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado");
                    return RedirectToAction("Index");
                }
                return View(cliente);
            }
            return View(new ClienteModel());
        }

        private bool ClienteExiste(int id)
        {
            return _context.Clientes.Any(o => o.IdUsuario == id);
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(int? id, [FromForm] ClienteModel cliente)
        {
            if(ModelState.IsValid)
            {
                if(id.HasValue)
                {
                    if(ClienteExiste(id.Value))
                    {
                        _context.Update(cliente);
                        _context.Entry(cliente).Property(o => o.Senha).IsModified = false;
                        if(await _context.SaveChangesAsync() > 0)
                        {
                            TempData["mensagem"] = MensagemModel.Serializar("Cliente alterado com sucesso");
                        }
                        else 
                        {
                            TempData["mensagem"] = MensagemModel.Serializar("Erro ao alterar Cliente", TipoMensagem.Erro);
                        }
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("cliente não encontrado", TipoMensagem.Erro);
                    }
                }
                else
                {
                    _context.Add(cliente);
                    if(await _context.SaveChangesAsync() > 0)
                    {
                         TempData["mensagem"] = MensagemModel.Serializar("Cliente cadastrada com sucesso");
                    }
                    else
                    {
                         TempData["mensagem"] = MensagemModel.Serializar("Erro ao cadastrar Cliente", TipoMensagem.Erro);
                    }
                   
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(cliente);
            }
        }
    
        [HttpGet]
        public async Task<IActionResult> Excluir(int? id)
        {
            if(!id.HasValue)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não informado", TipoMensagem.Erro);
                return RedirectToAction("Index");
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if(cliente == null)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado", TipoMensagem.Erro);
                return RedirectToAction("Index");   
            }
            return View(cliente);
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if(cliente != null)
            {
                _context.Clientes.Remove(cliente);
                if(await _context.SaveChangesAsync() > 0)
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Cliente excluída com sucesso");
                }
                else
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel excluir cliente", TipoMensagem.Erro);
                }
                return RedirectToAction("Index");
            }
            else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index));
            }
            
        }
    }

}

Controllers/PedidoController.cs
using System.Linq;
using System.Threading.Tasks;
using EstoqueWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EstoqueWeb.Controllers
{
    public class PedidoController : Controller {
        private readonly EstoqueWebContext _context;

        public PedidoController(EstoqueWebContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? cid)
        {
            if(cid.HasValue)
            {
                var cliente = await _context.Clientes.FirstOrDefaultAsync(c => c.IdUsuario == cid);
                if(cliente != null)
                {
                    var pedidos = await _context.Pedidos
                        .Where(p => p.IdCliente == cid)
                        .OrderByDescending(x => x.IdPedido)
                        .AsNoTracking().ToListAsync();
                    
                    ViewBag.Cliente = cliente;
                    return View(pedidos);
                }
                else
                {
                     TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado !", TipoMensagem.Erro);
                    return RedirectToAction("Index", "Cliente");
                }
            }else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Nenhum Cliente informado !", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Cadastrar(int? cid)
        {
            if(cid.HasValue)
            {
                var cliente = await _context.Clientes.FindAsync(cid);
                if(cliente != null)
                {
                    _context.Entry(cliente).Collection(c => c.Pedidos).Load();
                    PedidoModel pedido = null;
                    if(_context.Pedidos.Any(p => p.IdCliente == cid && !p.DataPedido.HasValue))
                    {
                        pedido = await _context.Pedidos.FirstOrDefaultAsync(p => p.IdCliente == cid && !p.DataPedido.HasValue);
                    }
                    else
                    {
                        pedido = new PedidoModel { IdCliente = cid.Value, ValorTotal = 0};
                        cliente.Pedidos.Add(pedido);
                        await _context.SaveChangesAsync();
                    }
                    return RedirectToAction("Index", "ItemPedido", new { ped = pedido.IdPedido});
                }
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado !", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Cliente não informado !", TipoMensagem.Erro);
            return RedirectToAction("Index", "Cliente");
        }

        private bool PedidoExiste(int id)
        {
            return _context.Pedidos.Any(o => o.IdPedido == id);
        }

        // [HttpPost]
        // public async Task<IActionResult> Cadastrar(int? id, [FromForm] PedidoModel cliente)
        // {
        //     if(ModelState.IsValid)
        //     {
        //         if(id.HasValue)
        //         {
        //             if(PedidoExiste(id.Value))
        //             {
        //                 _context.Update(cliente);
        //                 _context.Entry(cliente).Property(o => o.Senha).IsModified = false;
        //                 if(await _context.SaveChangesAsync() > 0)
        //                 {
        //                     TempData["mensagem"] = MensagemModel.Serializar("Pedido alterado com sucesso");
        //                 }
        //                 else 
        //                 {
        //                     TempData["mensagem"] = MensagemModel.Serializar("Erro ao alterar Pedido", TipoMensagem.Erro);
        //                 }
        //             }
        //             else
        //             {
        //                 TempData["mensagem"] = MensagemModel.Serializar("cliente não encontrado", TipoMensagem.Erro);
        //             }
        //         }
        //         else
        //         {
        //             _context.Add(cliente);
        //             if(await _context.SaveChangesAsync() > 0)
        //             {
        //                  TempData["mensagem"] = MensagemModel.Serializar("Pedido cadastrada com sucesso");
        //             }
        //             else
        //             {
        //                  TempData["mensagem"] = MensagemModel.Serializar("Erro ao cadastrar Pedido", TipoMensagem.Erro);
        //             }
                   
        //         }
        //         return RedirectToAction(nameof(Index));
        //     }
        //     else
        //     {
        //         return View(cliente);
        //     }
        // }
    
        [HttpGet]
        public async Task<IActionResult> Excluir(int? id)
        {
            if(!id.HasValue)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não informado", TipoMensagem.Erro);
                return RedirectToAction("Index");
            }

            var cliente = await _context.Pedidos.FindAsync(id);
            if(cliente == null)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado", TipoMensagem.Erro);
                return RedirectToAction("Index");   
            }
            return View(cliente);
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            var cliente = await _context.Pedidos.FindAsync(id);
            if(cliente != null)
            {
                _context.Pedidos.Remove(cliente);
                if(await _context.SaveChangesAsync() > 0)
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Pedido excluída com sucesso");
                }
                else
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Não foi possivel excluir cliente", TipoMensagem.Erro);
                }
                return RedirectToAction("Index");
            }
            else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index));
            }
            
        }
    }

}

Views/Cliente/Cadastrar.cshtml
@model ClienteModel 
@{
    if(Context.Request.RouteValues.ContainsKey("id"))
    {
        ViewBag.Subtitulo = "Alteração de Cliente";
    }
    else
    {
        ViewBag.Subtitulo = "Cadastro de Cliente";
    }
}

<h1 class="text-primary">@ViewBag.Subtitulo</h1>
<hr>

<form asp-action="Cadastrar">
    <input type="hidden" asp-for="@Model.IdUsuario">
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.Nome">Nome: </label>
        <input type="text" asp-for="@Model.Nome" class="form-control col-sm-8 col-lg-4" autofocus>
        <span asp-validation-for="@Model.Nome" class="text-danger"></span> 
    </div>
    <div class="w-100"></div>
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.CPF">CPF: </label>
        <input type="text" asp-for="@Model.CPF" class="form-control col-sm-8 col-lg-4">
        <span asp-validation-for="@Model.CPF" class="text-danger"></span> 
    </div>
    <div class="w-100"></div>
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.Email">Email: </label>
        <input type="email" asp-for="@Model.Email" class="form-control col-sm-8 col-lg-4">
        <span asp-validation-for="@Model.Email" class="text-danger"></span> 
    </div>
    <div class="w-100"></div>
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.DataNascimento">Data de Nascimento: </label>
        <input type="date" asp-for="@Model.DataNascimento" class="form-control col-sm-8 col-lg-4">
        <span asp-validation-for="@Model.DataNascimento" class="text-danger"></span> 
    </div>
    @if(!Context.Request.RouteValues.ContainsKey("id"))
    {
        <div class="w-100">
            <div class="form-group col-sm-8 col-lg-4">
                <label asp-for="@Model.Senha">Senha:</label>
                <input asp-for="@Model.Senha" class="form-control" type="password">
                <span asp-validation-for="@Model.Senha" class="text-danger"></span>
            </div>
        </div>
    }
    else
    {
        <!--Implementação perigosa, isso deixa a senha em texto puro durante o carregamento da página 
        <input type="hidden" asp-for="@Model.Senha">
        -->
    }
    <div class="mt-3">
        <a asp-action="Index" class="btn btn-outline-secondary">Cancelar</a>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
</form>

Views/Cliente/Excluir.cshtml
@model ClienteModel
@{
    ViewBag.Subtitulo = "Exclusão de Cliente";
}

<h1 class="text-primary">@ViewBag.Subtitulo</h1>
<hr>
<h4>Deseja realmente excluir o Cliente <span class="text-danger">@Model.Nome</span>?</h4>

<form asp-action="Excluir">
    <input type="hidden" asp-for="@Model.IdUsuario">
    <div class="mt-3">
        <a asp-action="Index" class="btn btn-success">Não</a>
        <button type="submit" class="btn btn-danger">Sim</button>
    </div>
</form>

Views/Cliente/Index.cshtml
@model IEnumerable<ClienteModel>
@{
    ViewBag.Subtitulo = "Listagem de Clientes";
}

<header class="d-flex justify-content-between align-itens-center">
    <div>
        <h1 class="text-primary">@ViewBag.Subtitulo</h1>
    </div>
    <div>
        <a asp-action="Cadastrar" class="btn btn-primary">Novo Cliente</a>
    </div>
</header>
<hr>

<partial name="_Mensagem"></partial>

@if(Model.Count() > 0)
{
    <table class="table table-striped tabela-categoria">
        <thead>
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>CPF</th>
                <th>Idade</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cliente in Model)
            {
                <tr>
                    <td>@cliente.Nome</td>
                    <td>@cliente.Email</td>
                    <td>@cliente.CPF</td>
                    <td>@cliente.Idade</td>
                    <td>
                        <a asp-controller="Pedido" asp-action="Index" asp-route-cid="@cliente.IdUsuario" class="btn btn-sm btn-success">Pedidos</a>
                        <a asp-controller="Endereco" asp-action="Index" asp-route-cid="@cliente.IdUsuario" class="btn btn-sm btn-secondary">Endereços</a>
                        <a asp-action="Cadastrar" asp-route-id="@cliente.IdUsuario" class="btn btn-sm btn-secondary">Alterar</a>
                        <a asp-action="Excluir" asp-route-id="@cliente.IdUsuario" class="btn btn-sm btn-danger">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else 
{
    <p> Nenhuma cliente cadastrado !! </p>
}